
    create table Dummy (
        ehehehe bigint generated by default as identity (start with 1),
        id bigint not null,
        creationDate timestamp,
        modificationDate timestamp,
        version bigint not null,
        primary key (ehehehe, id)
    );
